version: '2.2'

services:
  claude_colissend_db:
    build: ./mariadb
    container_name: claude_colissend_db
    hostname: claude_colissend_db
    volumes:
      - /srv/colissend/data/mariadb:/var/lib/mysql
      - /srv/colissend/logs/mysql:/var/logs/mysql

  claude_colissend_php-fpm:
    build: ./php-fpm
    container_name: claude_colissend_php-fpm
    hostname: claude_colissend_php-fpm
    cpus: 1.00
    volumes:
      - /srv/colissend/data/www:/var/www/html
      - /srv/colissend/logs/php-fpm:/var/log/php
      - /srv/colissend/logs/cron:/var/log/cron
    user: root

  claude_colissend_nginx:
    build: ./nginx
    container_name: claude_colissend_nginx
    hostname: claude_colissend_nginx
    volumes:
      - /srv/colissend/data/www:/var/www/html
      - /srv/colissend/logs/nginx:/var/log/nginx

  claude_colissend_npm:
    build: ./node
    container_name: claude_colissend_npm
    hostname:  claude_colissend_npm
    volumes:
      - /srv/colissend/data/www:/var/www/html


  claude_colissend_redis:
    build: ./redis
    container_name: claude_colissend_redis
    hostname:  claude_colissend_redis
    volumes:
      - /srv/colissend/data/redis:/data
