version: '2.2'

#New version

services:
  claude_colissend_db:
    build: ./mariadb
    container_name: claude_colissend_db
    hostname: claude_colissend_db
    volumes:
      - /srv/colissend/data/mariadb:/var/lib/mysql
      - /srv/colissend/logs/mysql:/var/logs/mysql
    networks:
      - portal-net
      - database-net

  claude_colissend_php-fpm:
    build: ./php-fpm
    container_name: claude_colissend_php-fpm
    hostname: claude_colissend_php-fpm
    cpus: 1.0
    volumes:
      - /srv/colissend/data/www:/var/www/html
      - /srv/colissend/logs/php-fpm:/var/log/php
      - /srv/colissend/logs/cron:/var/log/cron
    user: root
    networks:
      - portal-net

  claude_colissend_nginx:
    build: ./nginx
    container_name: claude_colissend_nginx
    hostname: claude_colissend_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.colissend-secure.entrypoints=frontendsecure"
      - "traefik.http.routers.colissend-secure.service=colissend"
      - "traefik.http.routers.colissend-secure.tls=true"
      - "traefik.http.services.colissend.loadbalancer.server.port=80"
      - "traefik.http.middlewares.colissend-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.colissend-secure.middlewares=colissend-headers"
    volumes:
      - /srv/colissend/data/www:/var/www/html
      - /srv/colissend/logs/nginx:/var/log/nginx
    networks:
      - portal-net
      - proxy
      - traefik-net

  claude_colissend_redis:
    build: ./redis
    container_name: claude_colissend_redis
    hostname:  claude_colissend_redis
    volumes:
      - /srv/colissend/data/redis:/data
    networks:
      - portal-net
      - database-net
