version: '2.2'

services:
  claude_colissend_db:
    extends:
      file: common.yml
      service: claude_colissend_db
    restart: always
    environment:
      MYSQL_DATABASE: colissend
      MYSQL_ROOT_PASSWORD: mariapwd

  claude_colissend_php-fpm:
    extends:
      file: common.yml
      service: claude_colissend_php-fpm
    depends_on:
      - claude_colissend_redis
    restart: always
    build:
      args:
        phpini: php_prod.ini
    links:
      - claude_colissend_db

  claude_colissend_nginx:
    extends:
      file: common.yml
      service: claude_colissend_nginx
    restart: always
    depends_on:
      - claude_colissend_php-fpm
    build:
      args:
        nginxconf: nginx_prod.conf
    labels:
      - "traefik.http.routers.colissend.rule=Host(`colissend.com`)"
    links:
      - claude_colissend_php-fpm

  claude_colissend_redis:
    extends:
      file: common.yml
      service: claude_colissend_redis
    restart: always

  claude_colissend_npm:
    extends:
      file: common.yml
      service: claude_colissend_npm
    ports:
      - 4000:3000
      - 4001:3001
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]

networks:
  portal-net:
    external: true
  traefik-net:
    external: true
  proxy:
    external: true
  database-net:
    external: true
