version: '2.2'

services:
  claude_colissend_db:
    extends:
      file: common.yml
      service: claude_colissend_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariapwd

  claude_colissend_php-fpm:
    extends:
      file: common.yml
      service: claude_colissend_php-fpm
    depends_on:
      - claude_colissend_redis
    restart: always
    build:
      args:
        phpini: php_prod.ini
    links:
      - claude_colissend_db

  claude_colissend_nginx:
    extends:
      file: common.yml
      service: claude_colissend_nginx
    restart: always
    depends_on:
      - claude_colissend_php-fpm
    build:
      args:
        nginxconf: nginx_prod.conf
    volumes:
      - /etc/ssl/abus-bkp/chain.abus-kransysteme.de.crt:/etc/nginx/ssl/abus-kransysteme.de.crt
      - /etc/ssl/abus-bkp/abus-kransysteme.de.key:/etc/nginx/ssl/abus-kransysteme.de.key
    labels:
      - "traefik.http.routers.colissend-secure.rule=Host(`colissend.com`)"
      - "traefik.http.routers.colissend-secure.tls.certresolver=leresolver"
    links:
      - claude_colissend_php-fpm

  claude_colissend_redis:
    extends:
      file: common.yml
      service: claude_colissend_redis
    restart: always

networks:
  portal-net:
    external: true
  traefik-net:
    external: true
  proxy:
    external: true
  database-net:
    external: true
