version: '2.2'

services:
  claude_colissend_db:
    extends:
      file: common.yml
      service: claude_colissend_db
    restart: always
    networks:
      - proxy
    environment:
      MYSQL_DATABASE: colissend
      MYSQL_ROOT_PASSWORD: mariapwd

  claude_colissend_php-fpm:
    extends:
      file: common.yml
      service: claude_colissend_php-fpm
    depends_on:
      - claude_colissend_redis
    restart: always
    build:
      args:
        phpini: php_prod.ini
    links:
      - claude_colissend_db
    networks:
      - proxy

  claude_colissend_nginx:
    extends:
      file: common.yml
      service: claude_colissend_nginx
    restart: always
    depends_on:
      - claude_colissend_php-fpm
    build:
      args:
        nginxconf: nginx_prod.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.colissend.rule=Host(`colissend.com`)"
    links:
      - claude_colissend_php-fpm
    networks:
      - proxy

  claude_colissend_redis:
    extends:
      file: common.yml
      service: claude_colissend_redis
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
